/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

public class LibraryTest {
	public static void main(String[] args) {
		
		int arr[] = {7,2,6,4,3,6};
		int temp;
		
		
		for(int i=0;i<arr.length-1;i++){
			
			boolean swapped = false;
			
			for(int j=0;j<arr.length - i -1;j++) {
				
				
				if (arr[j] > arr[j + 1]) {
					
					temp = arr[j]; 
					arr[j] = arr[j + 1]; 
					arr[j + 1] = temp; 
					swapped = true;
				}
				
				
			}
			
			if (swapped == false) 
				break;	
		     }
 		
	for(int k: arr) {
		
		System.out.print(k);
	}
   
}
}
//1 = 2,5,5,6,6,7,2
//2 = 5,,5,5